- name: Configure HTTP instance
  hosts: http
  become: yes
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes

- name: Configure SCRIPT instance
  hosts: script
  become: yes
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - docker-ce
          - php8.3-cli
          - php8.3-fpm
          - php8.3-mysql
          - php8.3-xml
          - php8.3-mbstring
          - php8.3-curl
          - php8.3-zip
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull WordPress Docker image
      docker_image:
        name: wordpress
        source: pull

    - name: Create Docker container for WordPress
      docker_container:
        name: wordpress
        image: wordpress
        environment:
          WORDPRESS_DB_HOST: "data-instance:3306"
          WORDPRESS_DB_USER: "user"
          WORDPRESS_DB_PASSWORD: "password"
          WORDPRESS_DB_NAME: "wordpress_db"
        ports:
          - "8080:80"
        volumes:
          - /app:/var/www/html

- name: Configure DATA instance
  hosts: data
  become: yes
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install MariaDB
      apt:
        name: mariadb-server
        state: present

    - name: Start MariaDB service
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Secure MariaDB installation
      mysql_secure_installation:
        login_password: ""
        root_password: "rootpassword" # Remplacez par un mot de passe fort
        remove_anonymous_user: yes
        disallow_root_login_remotely: yes
        remove_test_database: yes
        create_admin_user: yes
        admin_user: "user"
        admin_password: "password"
